# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:27:00

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Create scatter plot
    fig = px.scatter(
        data_raw,
        x="100g_USD",
        y="rating",
        title="Relationship Between 100g_USD and Rating",
        labels={"100g_USD": "100g_USD", "rating": "rating"},
        hover_data=["100g_USD", "rating"]
    )

    fig.update_traces(marker=dict(size=7, opacity=0.8), selector=dict(mode='markers'))

    fig.update_layout(
        xaxis_title="100g_USD",
        yaxis_title="rating",
        title_x=0.5
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict