# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 11:56:39

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create pie chart using "rating" as labels and "percentage" as values
    fig = go.Figure(go.Pie(labels=data_raw["rating"], values=data_raw["percentage"], 
                           hoverinfo='label+percent', textinfo='label+percent'))

    fig.update_layout(title_text="Percentage Distribution by Rating")

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict