# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:42:08

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Since the dataset has only one median value per PaymentMode,
    # a box plot is not meaningful with a single value per category.
    # To still fulfill the instruction, we will create a box plot but use
    # the median values as the data points for each PaymentMode.
    # This will look like a set of single points because of only one value each.

    # Prepare data for box plot: replicate median values to simulate distribution
    # Here, replicate each median 10 times to form a minimal distribution for visualization
    expanded_data = []
    for _, row in data_raw.iterrows():
        expanded_data.extend([{
            'PaymentMode': row['PaymentMode'],
            'median': row['median']
        }] * 10)
    df_expanded = pd.DataFrame(expanded_data)

    fig = go.Figure()

    payment_modes = df_expanded['PaymentMode'].unique()
    for mode in payment_modes:
        mode_data = df_expanded[df_expanded['PaymentMode'] == mode]['median']
        fig.add_trace(go.Box(y=mode_data, name=mode))

    fig.update_layout(
        title="Distribution of Median Values Across Payment Modes",
        yaxis_title="Median",
        xaxis_title="PaymentMode",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict