# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:46:29

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Compute correlation matrix
    corr_matrix = data_raw.corr()

    # Prepare heatmap
    fig = go.Figure(data=go.Heatmap(
        z=corr_matrix.values,
        x=corr_matrix.columns,
        y=corr_matrix.index,
        colorscale='Viridis',
        zmin=-1,
        zmax=1,
        colorbar=dict(title="Correlation")
    ))

    fig.update_layout(
        title="Correlation Matrix Heatmap",
        xaxis=dict(tickmode='array', tickvals=corr_matrix.columns, tickangle=45),
        yaxis=dict(tickmode='array', tickvals=corr_matrix.index),
        width=600,
        height=600,
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict