# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:18:47

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Pivot the data to create a matrix with roaster as columns, roast as rows
    # Values are average_rating - if duplicates exist, take the mean
    pivot_df = data_raw.pivot_table(index='roast', columns='roaster', values='average_rating', aggfunc='mean')

    # To improve readability of y-axis, sort roast levels if possible
    # Common roast order: Light, Medium, Medium-Dark, Dark, etc.
    # We have 5 unique roasts. We'll sort by roast intensity roughly:
    roast_order = ['Light', 'Medium', 'Medium-Dark', 'Dark', 'French']
    # Filter roast_order if some don't exist in the data
    roast_order_filtered = [r for r in roast_order if r in pivot_df.index]
    # If none of the common roasts match, just keep current order
    if len(roast_order_filtered) > 0:
        pivot_df = pivot_df.reindex(roast_order_filtered)

    # Prepare heatmap data
    z_data = pivot_df.values
    x_labels = pivot_df.columns.tolist()
    y_labels = pivot_df.index.tolist()

    # Create heatmap figure
    fig = go.Figure(data=go.Heatmap(
        z=z_data,
        x=x_labels,
        y=y_labels,
        colorscale='Viridis',
        colorbar=dict(title='Average Rating'),
        zmin=np.nanmin(z_data),
        zmax=np.nanmax(z_data),
        hovertemplate='Roaster: %{x}<br>Roast: %{y}<br>Avg Rating: %{z:.2f}<extra></extra>'
    ))

    fig.update_layout(
        title='Average Coffee Rating by Roaster and Roast',
        xaxis_title='Roaster',
        yaxis_title='Roast',
        yaxis=dict(autorange='reversed'),  # keep roast order top to bottom as in list
        template='plotly_white',
        width=900,
        height=500
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict