# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:47:14

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure index is a column for x-axis
    data = data_raw.copy()
    data = data.reset_index().rename(columns={'index': 'Category'})

    categories = data['Category']
    fatal = data['Fatal']
    non_fatal = data['Non-fatal']

    fig = go.Figure(data=[
        go.Bar(
            name='Fatal',
            x=categories,
            y=fatal,
            marker_color='crimson'
        ),
        go.Bar(
            name='Non-fatal',
            x=categories,
            y=non_fatal,
            marker_color='steelblue'
        )
    ])

    fig.update_layout(
        barmode='group',
        title='Comparison of Fatal and Non-fatal Counts Across Categories',
        xaxis_title='Category',
        yaxis_title='Count',
        legend_title_text='Type',
        xaxis_tickangle=-30,
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict