# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 19:29:21

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json



    # Create the figure with two histograms
    fig = go.Figure()

    # Add histogram for Offender_Age with blue color
    fig.add_trace(
        go.Histogram(
            x=data_raw['Offender_Age'],
            name='Offender_Age',
            marker_color='blue',
            opacity=0.75,
            nbinsx=30,
        )
    )

    # Add histogram for Victim_Age with red color
    fig.add_trace(
        go.Histogram(
            x=data_raw['Victim_Age'],
            name='Victim_Age',
            marker_color='red',
            opacity=0.75,
            nbinsx=30,
        )
    )

    # Update layout for better comparison
    fig.update_layout(
        barmode='overlay',
        title='Distribution of Offender and Victim Ages',
        xaxis_title='Age',
        yaxis_title='Count',
        legend_title='Age Type',
        template='plotly_white',
    )

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)

    fig_dict = json.loads(fig_json)
    return fig_dict