# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:09:40

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the bar chart with specified parameters
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['job_title'],
                y=data_raw['average_salary_in_usd'],
                marker=dict(color='blue')
            )
        ],
        layout=go.Layout(
            xaxis_title='job_title',
            yaxis_title='average_salary_in_usd'
        )
    )

    # Convert the figure to JSON and then back to dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict