# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:35:33

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create box plot for Budget (in Billion $) by Country
    fig = go.Figure()

    countries = data_raw['Country'].unique()
    for country in sorted(countries):
        country_data = data_raw[data_raw['Country'] == country]['Budget (in Billion $)']
        fig.add_trace(go.Box(
            y=country_data,
            name=country,
            boxmean='sd'  # show mean and standard deviation
        ))

    fig.update_layout(
        title="Distribution of Budget (in Billion $) by Country",
        xaxis_title="Country",
        yaxis_title="Budget (in Billion $)",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict