# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 03:31:26

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare the figure
    fig = go.Figure()

    # Extract categories
    categories = data_raw['roast'].tolist()

    # Extract corresponding stats as lists for the box plot parameters
    lowerfence = data_raw['min'].tolist()
    q1 = data_raw['q1'].tolist()
    median = data_raw['median'].tolist()
    q3 = data_raw['q3'].tolist()
    upperfence = data_raw['max'].tolist()

    # Add a single box trace with all category stats, using the box trace's boxpoints=False and specifying quartiles manually
    fig.add_trace(go.Box(
        x=categories,
        lowerfence=lowerfence,
        q1=q1,
        median=median,
        q3=q3,
        upperfence=upperfence,
        quartilemethod="linear",
        boxpoints=False,
        fillcolor='lightblue',
        line=dict(color='blue'),
        marker_color='blue',
        boxmean=False,
        showlegend=False
    ))

    fig.update_layout(
        title="Rating Distribution by Roast",
        yaxis_title="Rating",
        xaxis_title="Roast",
        yaxis=dict(range=[data_raw['min'].min() - 1, data_raw['max'].max() + 1]),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict