# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 18:42:52

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Scatter plot with:
    # X-axis: Total_Quantity
    # Y-axis: Total_Sales
    # Hover labels: Product names

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data_raw['Total_Quantity'],
        y=data_raw['Total_Sales'],
        mode='markers',
        marker=dict(size=10, color='blue', opacity=0.8),
        text=data_raw['Product'],
        hoverinfo='text+x+y',
        name='Products'
    ))

    fig.update_layout(
        title="Sales Efficiency and Volume Relationship per Product",
        xaxis_title="Quantity Sold (Total Quantity)",
        yaxis_title="Total Sales (Revenue)",
        xaxis=dict(range=[data_raw['Total_Quantity'].min()*0.9, data_raw['Total_Quantity'].max()*1.1]),
        yaxis=dict(range=[data_raw['Total_Sales'].min()*0.9, data_raw['Total_Sales'].max()*1.1]),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict