# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:39:47

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create scatter plot
    fig = go.Figure(
        data=go.Scatter(
            x=data_raw["Offender_Age"],
            y=data_raw["Victim_Age"],
            mode='markers',
            marker=dict(
                color='rgba(31, 119, 180, 0.7)',
                size=7,
                line=dict(width=0.5, color='rgba(0,0,0,0.2)')
            )
        )
    )

    fig.update_layout(
        title="Relationship between Offender_Age and Victim_Age",
        xaxis_title="Offender_Age",
        yaxis_title="Victim_Age",
        template="plotly_white",
        margin=dict(l=60, r=30, t=60, b=60)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict