# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 17:17:07

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Data is assumed clean as per instructions, no missing values or further cleaning needed

    fig = go.Figure(
        data=go.Bar(
            x=data_raw["Product_Type"],
            y=data_raw["Total_Quantity_Sold"],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title="Comparison of Quantities Sold by Product Type to Identify Popularity and Sales Variability",
        xaxis_title="Product Type",
        yaxis_title="Total Quantity Sold",
        xaxis=dict(type='category'),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict