# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 20:03:59

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Use the provided data_raw dataframe directly
    df = data_raw

    fig = go.Figure(
        data=go.Scatter(
            x=df["Amount"],
            y=df["Profit"],
            mode='markers',
            marker=dict(color='blue', opacity=0.7),
            name="Orders"
        )
    )

    fig.update_layout(
        title="Scatter Plot of Amount vs Profit for All Orders",
        xaxis_title="Amount",
        yaxis_title="Profit",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict