# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:23:26

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    x = data_raw['100g_USD']
    y = data_raw['rating']

    # Scatter points
    scatter = go.Scatter(
        x=x,
        y=y,
        mode='markers',
        name='Data points',
        marker=dict(color='blue', opacity=0.7)
    )

    # Compute linear regression for best-fit line
    slope, intercept = np.polyfit(x, y, 1)
    x_line = np.array([x.min(), x.max()])
    y_line = slope * x_line + intercept

    regression_line = go.Scatter(
        x=x_line,
        y=y_line,
        mode='lines',
        name='Best-fit line',
        line=dict(color='red', width=2)
    )

    layout = go.Layout(
        title='Scatter plot of Price per 100g vs Rating with Best-Fit Line',
        xaxis=dict(title='100g_USD'),
        yaxis=dict(title='Rating'),
        template='plotly_white'
    )

    fig = go.Figure(data=[scatter, regression_line], layout=layout)

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict