# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:16:24

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create the bar chart
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['Offender_Gender'],
                y=data_raw['count'],
                marker_color='blue'
            )
        ],
        layout=go.Layout(
            xaxis_title='Offender_Gender',
            yaxis_title='count'
        )
    )

    # Convert the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict