# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:39:31

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Columns to plot
    metrics = ["Communication", "Navigation", "Research", "Spy", "Weather"]

    # Aggregate average by Mission Type (although data is already one per Mission Type)
    df_avg = data_raw.groupby("Mission Type")[metrics].mean().reset_index()

    # Create traces for each metric
    fig = go.Figure()
    for metric in metrics:
        fig.add_trace(go.Bar(
            x=df_avg["Mission Type"],
            y=df_avg[metric],
            name=metric
        ))

    fig.update_layout(
        barmode='group',
        title="Average Success Rate (%) Across Mission Type by Mission Type",
        xaxis_title="Mission Type",
        yaxis_title="Average Success Rate (%)",
        legend_title="Mission Metrics",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict