# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:16:10

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Define age groups (y)
    age_groups = ["0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90+"]

    # Prepare traces for each age group
    traces = []
    for age in age_groups:
        traces.append(
            go.Bar(
                x=data_raw["Report Type"],
                y=data_raw[age],
                name=age
            )
        )

    fig = go.Figure(data=traces)
    fig.update_layout(
        barmode='group',
        title="Victim Counts by Report Type and Age Group",
        xaxis_title="Report Type",
        yaxis_title="Victim Count"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict