# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:21:12

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data
    df = data_raw.copy()

    # Create box plot grouped by "Have you ever had suicidal thoughts ?"
    fig = go.Figure()

    categories = df["Have you ever had suicidal thoughts ?"].unique()
    for cat in categories:
        fig.add_trace(go.Box(
            y=df.loc[df["Have you ever had suicidal thoughts ?"] == cat, "Work/Study Hours"],
            name=cat,
            boxmean='sd'
        ))

    fig.update_layout(
        title="Distribution of Work/Study Hours Grouped by Have you ever had suicidal thoughts ?",
        xaxis_title="Have you ever had suicidal thoughts ?",
        yaxis_title="Work/Study Hours"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict