# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:47:35

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data
    df = data_raw.copy()

    # Fix column name typo if exists
    # The error indicates 'Budget (in Billion $]' is misspelled (missing closing parenthesis)
    # Attempt to correct it to 'Budget (in Billion $)'
    if 'Budget (in Billion $]' in df.columns:
        df.rename(columns={'Budget (in Billion $]': 'Budget (in Billion $)'}, inplace=True)

    # Create scatter plot
    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=df["Budget (in Billion $)"],
            y=df["Success Rate (%)"],
            mode='markers',
            marker=dict(
                color='blue',
                size=6,
                opacity=0.7,
                line=dict(width=0.5, color='DarkSlateGrey')
            ),
            name='Data points'
        )
    )

    # Update layout with titles and axis labels
    fig.update_layout(
        title="Scatter Plot of Budget (in Billion $) vs Success Rate (%)",
        xaxis_title="Budget (in Billion $)",
        yaxis_title="Success Rate (%)",
        template="plotly_white"
    )

    # Convert figure to dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict