# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-11 18:40:49

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Grouping the data by 'job_title' and summing the 'count' for each title
    title_distribution = data_raw.groupby('job_title')['count'].sum().reset_index()

    # Creating the pie chart
    fig = go.Figure(data=[go.Pie(labels=title_distribution['job_title'], 
                                  values=title_distribution['count'], 
                                  textinfo='percent+label')])

    # Updating the layout of the figure
    fig.update_layout(title_text='Distribution of Job Titles in the Dataset')

    # Converting the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict