# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:12:05

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    df = data_raw.copy()

    fig = px.bar(
        df,
        x="roast",
        y="average_rating",
        color="roast",
        title="Average Rating by Roast Category",
        labels={"roast": "Roast", "average_rating": "Average Rating"},
        barmode='group'  # grouped is false, so default single bars
    )
    fig.update_layout(
        xaxis_title="Roast",
        yaxis_title="Average Rating",
        showlegend=False
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict