# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:05:48

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data: use budget and revenue columns
    # As per data description, budget and revenue have no missing values
    
    x = data_raw['budget']
    y = data_raw['revenue']

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=x,
        y=y,
        mode='markers',
        marker=dict(
            size=6,
            color='blue',
            opacity=0.6
        ),
        name='Movies'
    ))

    fig.update_layout(
        title='Scatter Plot of Budget vs Revenue',
        xaxis_title='Budget',
        yaxis_title='Revenue',
        template='plotly_white',
        hovermode='closest'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict