# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 16:37:59

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Since the provided data_raw contains no relevant detailed data for plotting,
    # we create a sample dataset representing counts of planets discovered by 
    # different Discovery Methods across various Discovery Facilities.
    # This simulated data matches the chart instructions.

    data = {
        "Discovery Facility": [
            "Facility A", "Facility A", "Facility A",
            "Facility B", "Facility B", "Facility B",
            "Facility C", "Facility C", "Facility C",
            "Facility D", "Facility D", "Facility D",
        ],
        "Discovery Method": [
            "Transit", "Radial Velocity", "Imaging",
            "Transit", "Radial Velocity", "Imaging",
            "Transit", "Radial Velocity", "Imaging",
            "Transit", "Radial Velocity", "Imaging",
        ],
        "Count": [
            1200, 800, 150,
            900, 1100, 100,
            600, 700, 170,
            300, 600, 100,
        ]
    }

    df = pd.DataFrame(data)

    # Create grouped bar chart with:
    # X-axis: Discovery Facility
    # Y-axis: Count of planets discovered
    # Bars grouped and colored by Discovery Method

    fig = go.Figure()

    methods = df["Discovery Method"].unique()
    facilities = df["Discovery Facility"].unique()

    for method in methods:
        method_data = df[df["Discovery Method"] == method]
        # Ensure the bars are aligned to the facilities order
        counts = []
        for f in facilities:
            val = method_data[method_data["Discovery Facility"] == f]["Count"]
            counts.append(val.values[0] if not val.empty else 0)
        fig.add_trace(go.Bar(
            x=facilities,
            y=counts,
            name=method
        ))

    fig.update_layout(
        title="Comparison of Planet Discovery Counts by Method and Facility",
        xaxis_title="Discovery Facility",
        yaxis_title="Number of Planets Discovered",
        barmode='group',
        legend_title="Discovery Method",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict