# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:24:58

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Count the number of ARRESTED for each Offender_Gender
    counts = data_raw.groupby('Offender_Gender')['ARRESTED'].sum().reset_index()

    # Create the bar chart
    fig = go.Figure(data=[
        go.Bar(
            x=counts['Offender_Gender'],
            y=counts['ARRESTED'],
            marker_color='blue'
        )
    ])

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict