# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:08:32

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio

    # Create a box plot of salary_in_usd vs experience_level with blue color
    fig = go.Figure()
    fig.add_trace(go.Box(
        y=data_raw['salary_in_usd'],
        x=data_raw['experience_level'],
        boxmean='sd',
        marker_color='blue'
    ))

    # Update layout for better presentation
    fig.update_layout(
        xaxis_title='Experience Level',
        yaxis_title='Salary in USD',
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict