# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:33:34

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create the box plot
    fig = go.Figure()

    # Get unique roast categories to maintain order
    roast_categories = data_raw['roast'].unique()
    
    for roast in roast_categories:
        roast_data = data_raw[data_raw['roast'] == roast]['rating']
        fig.add_trace(go.Box(
            y=roast_data,
            name=roast,
            boxmean='sd',
            marker=dict(outliercolor='rgba(219, 64, 82, 0.6)', line=dict(outliercolor='rgba(219, 64, 82, 1.0)', outlierwidth=2)),
            line=dict(width=1),
            showlegend=False
        ))

    fig.update_layout(
        title="Distribution of Rating by Roast",
        xaxis_title="Roast",
        yaxis_title="Rating",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict