# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:25:33

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create the bar chart with Offender_Gender on x-axis, Offender_Race on y-axis, and Count as bar height
    fig = go.Figure()

    # For each combination of Offender_Gender and Offender_Race, add a bar
    # Since the data is small, we can add a trace for each Offender_Gender
    genders = data_raw['Offender_Gender'].unique()
    for gender in genders:
        filtered_data = data_raw[data_raw['Offender_Gender'] == gender]
        fig.add_trace(
            go.Bar(
                x=filtered_data['Offender_Gender'],
                y=filtered_data['Count'],
                name=gender,
                marker_color='blue'
            )
        )

    # Update layout to set axes labels and title if needed
    fig.update_layout(
        barmode='group',
        xaxis_title='Offender_Gender',
        yaxis_title='Count'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict