# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:52:44

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Ensure input is a DataFrame
    df = pd.DataFrame(data_raw)

    # Only use rows where both Categorical_Var and Age_Type are not null
    df_plot = df[df['Categorical_Var'].notnull() & df['Age_Type'].notnull()]

    # Create box plot
    fig = px.box(
        df_plot,
        x="Categorical_Var",
        y="mean",
        color="Age_Type",
        points="all",
        title="Distribution of Mean Age by Categorical Variable and Age Type",
        labels={
            "Categorical_Var": "Categorical Variable",
            "mean": "Mean Age",
            "Age_Type": "Age Type"
        }
    )

    fig.update_layout(
        xaxis_title="Categorical Variable",
        yaxis_title="Mean Age",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict