# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 16:55:15

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure data is sorted by Discovery Year
    df = data_raw.sort_values(by="Discovery Year")

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df["Discovery Year"],
        y=df["Num Planets"],
        mode="lines+markers",
        line=dict(color="blue"),
        marker=dict(size=8),
        name="Num Planets"
    ))

    fig.update_layout(
        title="Trend of Discovered Planets Over Time (2008-2021)",
        xaxis_title="Discovery Year",
        yaxis_title="Number of Planets Discovered",
        xaxis=dict(tickmode="linear"),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict