# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:13:22

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Clean data: convert 'nan' string or actual NaN in roast to string 'nan' for plotting
    df = data_raw.copy()
    df['roast'] = df['roast'].astype(str)

    fig = go.Figure(
        data=go.Bar(
            x=df['roast'],
            y=df['avg_100g_USD'],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title="Average 100g Price (USD) by Roast Category",
        xaxis_title="Roast",
        yaxis_title="Average 100g Price (USD)",
        xaxis=dict(type='category')
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict