# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:50:49

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Calculate the average salary grouped by job_title
    grouped_data = data_raw.groupby('job_title', as_index=False)['salary_in_usd'].mean()

    # Create a bar chart with bars colored blue
    fig = go.Figure(
        data=[
            go.Bar(
                x=grouped_data['job_title'],
                y=grouped_data['salary_in_usd'],
                marker_color='blue'
            )
        ]
    )

    # Return the figure as a dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict