# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:54:19

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data
    df = data_raw.copy()

    # Fix country names to match plotly's expectations where needed
    country_replacements = {
        "England": "United Kingdom",
        "Hawai'i": "United States",
        "Hong Kong": "Hong Kong SAR",
        "New Taiwan": "Taiwan",
        "United States And Floyd": "United States"
    }
    df['country_plotly'] = df['loc_country'].replace(country_replacements)

    # Build the choropleth
    fig = go.Figure(
        data=go.Choropleth(
            locations=df["country_plotly"],
            locationmode="country names",
            z=df["avg_100g_USD"],
            colorscale="Viridis",
            colorbar_title="avg_100g_USD",
            text=df["loc_country"],  # show original name on hover
            hovertemplate='<b>%{text}</b><br>Average 100g USD: %{z:.2f}<extra></extra>'
        )
    )

    fig.update_layout(
        title_text="Average 100g USD Price by Country",
        geo=dict(
            showframe=False,
            showcoastlines=True,
            projection_type='natural earth'
        )
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict