# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:26:00

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create a box plot of salary_in_usd on y-axis and experience_level on x-axis
    fig = go.Figure()

    fig.add_trace(go.Box(
        y=data_raw['salary_in_usd'],
        x=data_raw['experience_level'],
        marker_color='blue',
        boxmean='sd'
    ))

    # Update layout for clarity and styling
    fig.update_layout(
        xaxis_title='Experience Level',
        yaxis_title='Salary in USD',
        boxmode='group',
        showlegend=False,
        template='plotly_white'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict