# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 15:48:09

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure Year_Month is sorted properly by converting to datetime
    data = data_raw.copy()
    data['Year_Month_dt'] = pd.to_datetime(data['Year_Month'], format='%Y-%m')
    data = data.sort_values('Year_Month_dt')

    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data['Year_Month'],
        y=data['Sales_Electronics'],
        mode='lines+markers',
        name='Electronics',
        line=dict(color='blue'),
        marker=dict(size=8)
    ))

    fig.add_trace(go.Scatter(
        x=data['Year_Month'],
        y=data['Sales_Clothing'],
        mode='lines+markers',
        name='Clothing',
        line=dict(color='red'),
        marker=dict(size=8)
    ))

    fig.update_layout(
        title="Monthly Trends in Average Total Sales for Electronics and Clothing",
        xaxis_title="Year-Month",
        yaxis_title="Average Total Sales",
        xaxis=dict(
            type='category',  # to show the Year-Month labels clearly as categories
            tickmode='array',
            tickvals=data['Year_Month'],
            tickangle=0,
            showgrid=False
        ),
        legend=dict(
            title="Category",
            x=0.01,
            y=0.99,
            bgcolor='rgba(255,255,255,0.8)',
            bordercolor='black',
            borderwidth=1
        ),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict