# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:43:54

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate data: average Budget by Country and Environmental Impact
    df_avg = data_raw.groupby(['Country', 'Environmental Impact'], as_index=False)['Budget (in Billion $)'].mean()

    # Get unique countries and environmental impacts for consistent ordering
    countries = df_avg['Country'].unique()
    env_impacts = df_avg['Environmental Impact'].unique()

    # Create a bar for each Environmental Impact category
    bars = []
    for impact in env_impacts:
        df_impact = df_avg[df_avg['Environmental Impact'] == impact]
        # Map the budget values corresponding to countries order
        budget_vals = [df_impact[df_impact['Country'] == c]['Budget (in Billion $)'].values[0] if c in df_impact['Country'].values else np.nan for c in countries]
        bars.append(
            go.Bar(
                name=impact,
                x=countries,
                y=budget_vals
            )
        )

    # Create the figure with grouped bars
    fig = go.Figure(data=bars)
    fig.update_layout(
        barmode='group',
        xaxis_title="Country",
        yaxis_title="Average Budget (in Billion $)",
        title="Average Budget by Country and Environmental Impact"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict