# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:30:28

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare the data
    df = data_raw.copy()

    # Create scatter plot of Units Sold vs Profit
    fig = go.Figure(
        data=go.Scatter(
            x=df['Units Sold'],
            y=df['Profit'],
            mode='markers',
            marker=dict(color='blue', size=7, opacity=0.7)
        )
    )

    # Update layout with title and axis labels
    fig.update_layout(
        title="Scatter Plot of Units Sold vs Profit",
        xaxis_title="Units Sold",
        yaxis_title="Profit",
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict