# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:14:53

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create bar chart
    fig = go.Figure(go.Bar(
        x=data_raw['roast'],
        y=data_raw['avg_100g_USD']
    ))

    fig.update_layout(
        title="Average 100g Price in USD Across Roast Categories",
        xaxis_title="Roast",
        yaxis_title="Average Price per 100g (USD)"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict