# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 22:46:26

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Extract the correlation coefficient value from the data
    corr_value = data_raw.loc[0, 'Sales_Quantity_Correlation']
    corr_rounded = round(corr_value, 4)

    # Create a single numeric indicator showing the correlation coefficient
    fig = go.Figure(go.Indicator(
        mode = "number+delta",
        value = corr_rounded,
        number = {
            'valueformat': '.4f',
            'suffix': '',
            'font': {'size': 72}
        },
        title = {
            'text': "Correlation between Total Sales and Quantity Sold in 2025<br><span style='font-size:24px;color:gray'>Pearson Correlation Coefficient</span>",
            'font': {'size': 24}
        },
        delta = {
            'reference': 0,
            'relative': False,
            'position': "bottom",
            'font': {'size': 18},
            'increasing': {'color': "green"},
            'decreasing': {'color': "red"}
        }
    ))

    fig.update_layout(
        height=300,
        margin=dict(t=80, b=40, l=40, r=40)
    )
    
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict