# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:36:38

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure the 'Year-Month' is treated as a category with the order preserved
    data_raw['Year-Month'] = pd.Categorical(data_raw['Year-Month'], categories=data_raw['Year-Month'].tolist(), ordered=True)

    fig = go.Figure()

    fig.add_trace(
        go.Scatter(
            x=data_raw['Year-Month'],
            y=data_raw['Amount'],
            mode='lines+markers',
            line=dict(color='blue'),
            marker=dict(size=6)
        )
    )

    fig.update_layout(
        title="Trends in Total Amount Over Year-Month",
        xaxis=dict(
            title="Year-Month",
            type='category',
            tickangle=-45
        ),
        yaxis=dict(
            title="Amount"
        ),
        margin=dict(l=60, r=40, t=80, b=120)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict