# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:38:15

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    fig = px.bar(
        data_raw,
        x="Offender_Gender",
        y="RecordCount",
        color="OffenderStatus",
        color_discrete_sequence=px.colors.sequential.Greens,
        barmode="stack",
        title="Distribution of Offender Status by Gender",
    )

    fig.update_layout(
        xaxis_title="Gender",
        yaxis_title="Count of Offender Status",
        legend_title="Offender Status",
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict