# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:16:46

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data_raw["Academic Pressure"],
        y=data_raw["Depression"],
        mode='markers',
        marker=dict(
            color='blue',
            opacity=0.6,
            size=6
        ),
        name="Data Points"
    ))

    fig.update_layout(
        title="Scatter Plot of Academic Pressure vs Depression",
        xaxis_title="Academic Pressure",
        yaxis_title="Depression",
        yaxis=dict(tickmode='array', tickvals=[0,1], ticktext=["No Depression","Depression"]),
        template="plotly_white",
        height=500,
        width=700
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict