# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 15:06:47

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Extract data for plotting
    locations = data_raw['Customer Location']
    sales = data_raw['Total Sales']

    # Use a distinct color for each bar by using a qualitative colorscale
    colors = px_colors = [
        '#636EFA', '#EF553B', '#00CC96', '#AB63FA',
        '#FFA15A', '#19D3F3', '#FF6692', '#B6E880', '#FF97FF'
    ]
    # Ensure number of colors matches number of bars
    bar_colors = colors[:len(locations)]

    fig = go.Figure(
        data=go.Bar(
            x=locations,
            y=sales,
            marker_color=bar_colors,
            hovertemplate='Average Total Sales: %{y:.2f}<extra></extra>'
        )
    )

    fig.update_layout(
        title="Average Total Sales by Customer Location to Reveal Geographic Purchasing Patterns",
        xaxis_title="Customer Location",
        yaxis_title="Average Total Sales",
        xaxis=dict(type='category'),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict