# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:07:49

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json



    # Create bar chart with Plotly Graph Objects
    fig = go.Figure(data=[
        go.Bar(
            x=data_raw['job_title'],
            y=data_raw['average_salary_in_usd'],
            marker_color='blue'
        )
    ])

    # Update layout for better readability
    fig.update_layout(
        title='Average Salary in USD by Job Title',
        xaxis_title='Job Title',
        yaxis_title='Average Salary in USD',
        xaxis_tickangle=45,
        margin=dict(b=150),
        height=600
    )

    # Convert figure to JSON for return
    fig_json = pio.to_json(fig)

    fig_dict = json.loads(fig_json)
    return fig_dict