# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:24:33

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure the data is a DataFrame
    df = pd.DataFrame(data_raw)

    # Since there are only two rows, a box plot will simply show each median value as a point.
    # Plotly requires a distribution for a box plot; with two values, we can still construct the box plot.
    fig = go.Figure()

    for _, row in df.iterrows():
        fig.add_trace(
            go.Box(
                y=[row['median']],  # Single median value per report type
                name=row['Report Type'],
                boxpoints='all',  # show all points
                jitter=0.3,
                pointpos=0,
                marker=dict(size=8),
                line=dict(width=1),
                showlegend=False
            )
        )

    fig.update_layout(
        title="Distribution of Median Values by Report Type",
        xaxis_title="Report Type",
        yaxis_title="median",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict