# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:57:41

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Standardize country names for better matching with plotly's country codes
    country_replacements = {
        "England": "United Kingdom",
        "Hawai'i": "United States",
        "Hong Kong": "Hong Kong SAR",
        "New Taiwan": "Taiwan",
        "United States And Floyd": "United States"
    }
    data = data_raw.copy()
    data['country_for_map'] = data['loc_country'].replace(country_replacements)

    # Create the choropleth map
    fig = go.Figure(
        go.Choropleth(
            locations=data['country_for_map'],
            locationmode='country names',
            z=data['avg_100g_USD'],
            colorscale='Viridis',
            colorbar_title='Avg 100g USD',
            text=data['loc_country'] + ": $" + data['avg_100g_USD'].round(2).astype(str),
            marker_line_color='white'
        )
    )

    fig.update_layout(
        title_text="Average 100g USD Price by Country",
        geo=dict(
            showframe=False,
            showcoastlines=True,
            projection_type='equirectangular'
        ),
        margin=dict(l=0, r=0, t=50, b=0)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict