# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:34:41

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create the violin plot
    fig = go.Figure()

    countries = data_raw['Country'].unique()
    for country in countries:
        country_data = data_raw[data_raw['Country'] == country]['Budget (in Billion $)']
        fig.add_trace(go.Violin(
            x=[country] * len(country_data),
            y=country_data,
            name=country,
            box_visible=True,
            meanline_visible=True,
            points="all",
            jitter=0.5,
            scalemode='count'
        ))

    fig.update_layout(
        title="Distribution of Budget (in Billion $) by Country",
        xaxis_title="Country",
        yaxis_title="Budget (in Billion $)",
        violingap=0,
        violingroupgap=0,
        violinmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict