# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 16:34:07

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure the data is sorted by 'Discovery Year'
    df = data_raw.sort_values(by='Discovery Year')

    # Since each year is unique, average is just the value itself, but we follow instructions
    avg_df = df.groupby('Discovery Year', as_index=False)['Orbital Period Days'].mean()

    # Create line chart with markers
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=avg_df['Discovery Year'],
        y=avg_df['Orbital Period Days'],
        mode='lines+markers',
        line=dict(color='blue'),
        marker=dict(size=8),
        name='Average Orbital Period Days'
    ))

    fig.update_layout(
        title="Trend of Average Orbital Period Days by Discovery Year",
        xaxis_title="Discovery Year",
        yaxis_title="Average Orbital Period (Days)",
        xaxis=dict(showgrid=True, zeroline=False, dtick=1),
        yaxis=dict(showgrid=True, zeroline=False),
        template='simple_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict