# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 03:27:48

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data for plotting
    df = data_raw.copy()

    # Create scatter plot
    fig = go.Figure(data=go.Scatter(
        x=df['100g_USD'],
        y=df['rating'],
        mode='markers',
        marker=dict(
            size=7,
            color=df['rating'],  # Color points by rating for better insight
            colorscale='Viridis',
            showscale=True,
            colorbar=dict(title='Rating')
        ),
        text=df['name'],  # show coffee name on hover
        hovertemplate=
            '<b>%{text}</b><br>' +
            'Price per 100g (USD): %{x}<br>' +
            'Rating: %{y}<extra></extra>'
    ))

    fig.update_layout(
        title="Scatter Plot of 100g_USD vs Rating",
        xaxis_title="Price per 100g (USD)",
        yaxis_title="Rating",
        template="plotly_white",
        hovermode='closest'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict