# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:27:08

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=data_raw["Date"],
        y=data_raw["Profit"],
        mode='lines+markers',
        name='Profit'
    ))

    fig.update_layout(
        title="Trend of Profit Over Date",
        xaxis_title="Date",
        yaxis_title="Profit",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict