# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:12:34

def data_visualization(data_raw):
    import pandas as pd
    import plotly.express as px
    import json
    import plotly.io as pio




    # Create a box plot with Offender_Age vs Offender_Race, colored blue
    fig = px.box(
        data_raw,
        x='Offender_Race',
        y='Offender_Age',
        color_discrete_sequence=['blue']
    )

    # Convert the figure to JSON and then back to dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict