# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:54:16

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Group data by job_title and M, then calculate mean of L
    grouped = data_raw.groupby(['job_title', 'M'], as_index=False).agg({'L': 'mean'})

    # Create the bar chart with grouped data
    fig = go.Figure()

    # Get unique M categories for grouping
    M_categories = grouped['M'].unique()

    # For each M category, add a bar trace
    for m_value in M_categories:
        df_subset = grouped[grouped['M'] == m_value]
        fig.add_trace(
            go.Bar(
                x=df_subset['job_title'],
                y=df_subset['L'],
                name=str(m_value),
                marker_color='blue'
            )
        )

    # Update layout to group bars
    fig.update_layout(
        barmode='group',
        xaxis_title='job_title',
        yaxis_title='Average of L',
        title='Average of L by job_title grouped by M'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict