# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-21 16:28:20

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is expected to be a DataFrame with index as years 2000-2024 and columns "High", "Low", "Medium"
    df = data_raw.copy()
    df.index = df.index.astype(int)  # ensure index are integers
    
    years = list(range(2000, 2025))
    
    # Prepare the figure
    fig = go.Figure()
    
    # Add traces for each category
    fig.add_trace(go.Scatter(
        x=years,
        y=df.loc[years, 'High'],
        mode='lines+markers',
        name='High',
        line=dict(color='red'),
    ))
    fig.add_trace(go.Scatter(
        x=years,
        y=df.loc[years, 'Medium'],
        mode='lines+markers',
        name='Medium',
        line=dict(color='green'),
    ))
    fig.add_trace(go.Scatter(
        x=years,
        y=df.loc[years, 'Low'],
        mode='lines+markers',
        name='Low',
        line=dict(color='blue'),
    ))
    
    # Update layout with titles and axis labels
    fig.update_layout(
        title="Trends in Average Per Capita Water Use Over Time by Water Scarcity Level",
        xaxis_title="Year",
        yaxis_title="Average Per Capita Water Use (Liters per Day)",
        xaxis=dict(
            tickmode='array',
            tickvals=years,
            tickangle=45,
            dtick=1,
            range=[years[0], years[-1]],
            showgrid=True,
        ),
        legend_title_text="Water Scarcity Level",
        template="plotly_white",
        margin=dict(l=60, r=20, t=80, b=80),
    )
    
    # Convert fig to json dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    
    return fig_dict