# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:26:58

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create the bar chart with Offender_Gender on x-axis and Count on y-axis
    fig = go.Figure(
        data=[go.Bar(
            x=data_raw['Offender_Gender'],
            y=data_raw['Count'],
            marker_color='blue'
        )]
    )

    # Convert the figure to JSON and then to a Python dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict