# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 19:55:23

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate Quantity by Sub-Category (sum)
    df_agg = data_raw.groupby('Sub-Category', as_index=False)['Quantity'].sum()

    # Create bar chart
    fig = go.Figure(
        data=go.Bar(
            x=df_agg['Sub-Category'],
            y=df_agg['Quantity'],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title='Total Quantity Sold for Each Sub-Category',
        xaxis_title='Sub-Category',
        yaxis_title='Total Quantity',
        xaxis_tickangle=-45,
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict