# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:17:52

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate data by Age, compute average Depression
    df_agg = data_raw.groupby('Age', as_index=False)['Depression'].mean()

    # Create line chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df_agg['Age'],
        y=df_agg['Depression'],
        mode='lines+markers',
        line=dict(color='blue'),
        name='Average Depression'
    ))

    fig.update_layout(
        title='Trend of Average Depression by Age',
        xaxis_title='Age',
        yaxis_title='Average Depression',
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict