# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:04:04

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the box plot with experience_level on x-axis and salary_in_usd as y-axis, color set to blue
    fig = go.Figure()

    # Add box trace
    fig.add_trace(go.Box(
        x=data_raw['experience_level'],
        y=data_raw['salary_in_usd'],
        boxmean='sd',  # Optional: show mean and std dev
        marker_color='blue',
        boxpoints='outliers',  # Show outliers
        line=dict(color='blue')
    ))

    # Update layout to set title and axes labels if needed
    fig.update_layout(
        title='Salary Distribution by Experience Level',
        xaxis_title='Experience Level',
        yaxis_title='Salary in USD'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict