# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-19 18:28:44

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate data: mean rating by loc_country and origin
    pivot_table = data_raw.pivot_table(
        index='loc_country',
        columns='origin',
        values='rating',
        aggfunc='mean'
    )

    # Sort index and columns for consistent ordering
    pivot_table = pivot_table.sort_index()
    pivot_table = pivot_table.reindex(sorted(pivot_table.columns), axis=1)

    fig = go.Figure(data=go.Heatmap(
        z=pivot_table.values,
        x=pivot_table.columns,
        y=pivot_table.index,
        colorscale='Viridis',
        colorbar=dict(title="Average rating"),
        hoverongaps=False
    ))

    fig.update_layout(
        title="Average Rating by loc_country and origin",
        xaxis_title="origin",
        yaxis_title="loc_country",
        xaxis=dict(tickangle=45)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict