# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:12:34

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create a box plot with salary_in_usd on y-axis and experience_level on x-axis, color blue
    fig = go.Figure()

    # Add box plot trace
    fig.add_trace(go.Box(
        y=data_raw['salary_in_usd'],
        x=data_raw['experience_level'],
        boxmean='sd',  # optional, for showing mean and std dev
        marker_color='blue'
    ))

    # Update layout for better readability
    fig.update_layout(
        xaxis_title='experience_level',
        yaxis_title='salary_in_usd',
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict