# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 16:30:51

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is expected to be a DataFrame with index as Category and columns as Payment Methods
    # Reset index to get Category as a column
    df = data_raw.copy()
    df = df.reset_index().rename(columns={'index': 'Category'})

    categories = df['Category'].tolist()
    payment_methods = ['Credit Card', 'Debit Card', 'Gift Card', 'PayPal']
    colors = {
        'Credit Card': '#636EFA',
        'Debit Card': '#EF553B',
        'Gift Card': '#00CC96',
        'PayPal': '#AB63FA'
    }

    fig = go.Figure()

    for pm in payment_methods:
        fig.add_trace(
            go.Bar(
                x=categories,
                y=df[pm],
                name=pm,
                marker_color=colors[pm]
            )
        )

    fig.update_layout(
        barmode='group',
        title="Average Order Quantity by Payment Method for Each Category",
        xaxis_title="Category",
        yaxis_title="Average Order Quantity",
        legend_title="Payment Method"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict