# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:48:11

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Use the data as is for the scatter plot
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data_raw['Amount'],
        y=data_raw['Profit'],
        mode='markers',
        marker=dict(
            color='blue',
            opacity=0.7,
            size=7
        )
    ))

    fig.update_layout(
        title="Scatter Plot of Amount vs Profit",
        xaxis_title="Amount",
        yaxis_title="Profit",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict