# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:59:18

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create box plot with PaymentMode on x-axis and Profit on y-axis
    fig = go.Figure()

    payment_modes = data_raw['PaymentMode'].unique()

    for mode in payment_modes:
        mode_data = data_raw[data_raw['PaymentMode'] == mode]['Profit']
        fig.add_trace(go.Box(
            y=mode_data,
            name=mode,
            boxmean='sd'  # show mean and standard deviation
        ))

    fig.update_layout(
        title="Distribution of Profit across Payment Modes",
        xaxis_title="Payment Mode",
        yaxis_title="Profit",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict