# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 16:24:31

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create bar chart
    fig = go.Figure()

    # Add bars with distinct colors automatically handled by Plotly
    fig.add_trace(go.Bar(
        x=data_raw['Status'],
        y=data_raw['Transaction Count'],
        text=data_raw['Transaction Count'],
        textposition='outside',
        marker_color=['#636EFA', '#EF553B', '#00CC96']  # Distinct colors for clarity
    ))

    # Update layout with titles and axis labels
    fig.update_layout(
        title="Transaction Counts by Status: Completed, Pending, and Cancelled",
        xaxis_title="Transaction Status",
        yaxis_title="Number of Transactions",
        yaxis=dict(tickformat='d'),  # Show y-axis ticks as integers
        uniformtext_minsize=8,
        uniformtext_mode='hide',
        template="simple_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict