# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:09:00

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    sub_categories = data_raw['Sub-Category'].unique()

    for sub_cat in sorted(sub_categories):
        profits = data_raw.loc[data_raw['Sub-Category'] == sub_cat, 'Profit']
        fig.add_trace(go.Box(y=profits,
                             name=sub_cat,
                             boxmean='sd'))

    fig.update_layout(
        title="Distribution of Profit across Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Profit",
        xaxis=dict(
            categoryorder='array',
            categoryarray=sorted(sub_categories)
        ),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict