# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:04:52

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data - no missing values in budget or revenue according to data description
    df = data_raw.copy()

    # Create scatter plot with budget on x-axis and revenue on y-axis
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df['budget'],
        y=df['revenue'],
        mode='markers',
        marker=dict(
            size=6,
            color='blue',
            opacity=0.6
        ),
        text=df['title'],
        hovertemplate=
            "<b>%{text}</b><br>" +
            "Budget: %{x:$,.0f}<br>" +
            "Revenue: %{y:$,.0f}<br>" +
            "<extra></extra>"
    ))

    fig.update_layout(
        title="Scatter Plot of Budget vs Revenue",
        xaxis_title="Budget",
        yaxis_title="Revenue",
        xaxis=dict(tickformat="$,.0f"),
        yaxis=dict(tickformat="$,.0f"),
        template="plotly_white",
        height=600,
        width=800
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict