# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 20:10:15

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate total Amount by Sub-Category
    agg_data = data_raw.groupby('Sub-Category', as_index=False)['Amount'].sum()

    # Create bar chart
    fig = go.Figure(
        data=go.Bar(
            x=agg_data['Sub-Category'],
            y=agg_data['Amount'],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title="Total Sales Amount by Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Total Amount",
        xaxis_tickangle=-45,
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict