# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 20:07:54

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate quantity by CustomerName (in case there are duplicates)
    df_agg = data_raw.groupby("CustomerName", as_index=False)["Quantity"].sum()

    # Sort by Quantity descending
    df_sorted = df_agg.sort_values(by="Quantity", ascending=False)

    fig = go.Figure(
        go.Bar(
            x=df_sorted["CustomerName"],
            y=df_sorted["Quantity"],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title="Quantity Bought by Each Customer",
        xaxis_title="CustomerName",
        yaxis_title="Quantity",
        xaxis=dict(
            tickangle=-45,
            tickfont=dict(size=8),
            categoryorder="array",
            categoryarray=df_sorted["CustomerName"]
        ),
        margin=dict(b=150),
        height=600,
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict