# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:20:52

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data_raw['release_year'],
        y=data_raw['average_revenue'],
        mode='lines+markers',
        line=dict(dash='solid'),
        marker=dict(symbol='circle')
    ))

    fig.update_layout(
        title="Trends in Average Revenue Over Release Year",
        xaxis_title="Release Year",
        yaxis_title="Average Revenue",
        xaxis=dict(tickmode='linear'),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict