# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:37:09

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create bar chart: Mean Offender Age by Offender Gender
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['Offender_Gender'],
                y=data_raw['mean'],
                marker_color=['#636EFA', '#EF553B']
            )
        ]
    )

    fig.update_layout(
        title='Mean Offender Age by Offender Gender',
        xaxis_title='Offender Gender',
        yaxis_title='Mean Age',
        bargap=0.4,
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict