# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 16:09:11

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure 'Date' column is datetime dtype (should already be, but just in case)
    data = data_raw.copy()
    if not np.issubdtype(data['Date'].dtype, np.datetime64):
        data['Date'] = pd.to_datetime(data['Date'])

    # Create line chart with markers
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data['Date'],
        y=data['Total Sales'],
        mode='lines+markers',
        line=dict(color='blue', width=2),
        marker=dict(size=6, color='red'),
        name='Total Sales'
    ))

    fig.update_layout(
        title="Trend of Total Sales Over Time",
        xaxis_title="Date",
        yaxis_title="Total Sales",
        xaxis=dict(
            type='date',
            tickformat='%Y-%m-%d',
            tickangle=45,
            showgrid=True
        ),
        yaxis=dict(
            showgrid=True
        ),
        template="plotly_white",
        margin=dict(l=60, r=40, t=60, b=80)
    )
    
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict