# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:45:02

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure numeric columns and drop missing values in x or y
    df = data_raw.copy()
    df = df.dropna(subset=['Offender_Age', 'Victim_Age'])

    # Create scatter plot
    fig = go.Figure(
        data=go.Scatter(
            x=df['Offender_Age'],
            y=df['Victim_Age'],
            mode='markers',
            marker=dict(
                size=7,
                opacity=0.7,
                color='rgba(44, 160, 101, 0.7)',
                line=dict(width=0.5, color='DarkSlateGrey')
            ),
            hovertemplate=
                'Offender_Age: %{x}<br>Victim_Age: %{y}<extra></extra>'
        )
    )

    fig.update_layout(
        title='Relationship between Offender_Age and Victim_Age',
        xaxis_title='Offender_Age',
        yaxis_title='Victim_Age',
        template='plotly_white',
        margin=dict(l=60, r=30, t=60, b=60)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict