# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:31:14

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Assuming data_raw is a pandas DataFrame with the specified columns
    fig = go.Figure()

    # Add a bar trace with job_title on x-axis and avg_salary_in_usd on y-axis
    fig.add_trace(
        go.Bar(
            x=data_raw['job_title'],
            y=data_raw['avg_salary_in_usd'],
            marker_color='blue'
        )
    )

    # Update layout for better readability
    fig.update_layout(
        xaxis_title='Job Title',
        yaxis_title='Average Salary in USD',
        xaxis_tickangle=45,
        margin=dict(b=150)
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict