# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:46:01

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create a bar chart with job_title on x-axis and average_salary_in_usd on y-axis
    fig = go.Figure(data=[
        go.Bar(
            x=data_raw['job_title'],
            y=data_raw['average_salary_in_usd'],
            marker_color='blue'
        )
    ])

    # Convert the figure to JSON and then to a dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict