# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 15:39:14

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Since there is only one price per category, we create a grouped bar chart with one bar per category
    df = data_raw.copy()

    # Create a bar trace for each category to have distinct colors
    # However, since each category has a single price, we can create one trace with different colors per bar
    colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA']  # distinct colors for each category

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=df['Category'],
        y=df['Price'],
        marker_color=colors,
        name="Price"
    ))

    fig.update_layout(
        title="Price Differences Across Product Categories",
        xaxis_title="Product Category",
        yaxis_title="Price",
        barmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict