# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:32:06

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Summing profits by segment for each country (data is already per country, so sum is the value itself)
    # But to be consistent with instructions, in case of multiple rows per country, groupby sum:
    df_sum = data_raw.groupby('Country', as_index=False)[
        "Channel Partners", "Enterprise", "Government", "Midmarket", "Small Business"
    ].sum()

    segments = ["Channel Partners", "Enterprise", "Government", "Midmarket", "Small Business"]

    fig = go.Figure()

    # Add one trace (bar) for each segment
    for segment in segments:
        fig.add_trace(go.Bar(
            x=df_sum['Country'],
            y=df_sum[segment],
            name=segment
        ))

    fig.update_layout(
        barmode='group',
        title="Sum of Profits by Segment and Country",
        xaxis_title="Country",
        yaxis_title="Sum of Profits",
        legend_title="Segment"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict