# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:46:33

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Calculate the mean remote_ratio for each job_title
    data_grouped = data_raw.groupby('job_title', as_index=False)['remote_ratio'].mean()

    # Create the bar chart with blue color
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_grouped['job_title'],
                y=data_grouped['remote_ratio'],
                marker_color='blue'
            )
        ],
        layout=go.Layout(
            xaxis_title='job_title',
            yaxis_title='Average remote_ratio',
            title='Average remote_ratio by job_title'
        )
    )

    # Convert the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict