# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:22:28

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Create scatter plot using plotly.express
    fig = px.scatter(
        data_raw,
        x="Work/Study Hours",
        y="Academic Pressure",
        title="Scatter Plot of Work/Study Hours vs Academic Pressure",
        labels={
            "Work/Study Hours": "Work/Study Hours",
            "Academic Pressure": "Academic Pressure"
        }
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict