# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:33:13

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Calculate average Budget by Environmental Impact and Satellite Type
    avg_budget = data_raw.groupby(['Environmental Impact', 'Satellite Type'], as_index=False)['Budget (in Billion $)'].mean()

    # Get unique Environmental Impact categories and Satellite Types for ordering
    env_impacts = avg_budget['Environmental Impact'].unique()
    sat_types = avg_budget['Satellite Type'].unique()

    # Create a bar trace for each Satellite Type
    fig = go.Figure()
    for sat in sat_types:
        filtered = avg_budget[avg_budget['Satellite Type'] == sat]
        # Ensure the order of Environmental Impact on x-axis is consistent
        filtered = filtered.set_index('Environmental Impact').reindex(env_impacts).reset_index()
        fig.add_trace(go.Bar(
            x=filtered['Environmental Impact'],
            y=filtered['Budget (in Billion $)'],
            name=sat
        ))

    fig.update_layout(
        barmode='group',
        xaxis_title='Environmental Impact',
        yaxis_title='Average Budget (in Billion $)',
        title='Average Budget by Environmental Impact and Satellite Type',
        legend_title='Satellite Type'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict