# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:39:02

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json



    # Create a box plot of salary_in_usd grouped by company_size with blue color
    fig = go.Figure()

    # Get unique company sizes
    company_sizes = data_raw['company_size'].unique()

    # Add box traces for each company size to ensure consistent coloring and grouping
    for size in company_sizes:
        filtered_data = data_raw[data_raw['company_size'] == size]
        fig.add_trace(
            go.Box(
                y=filtered_data['salary_in_usd'],
                name=size,
                marker_color='blue',
                boxmean=False
            )
        )

    # Update layout for clarity
    fig.update_layout(
        yaxis_title='salary_in_usd',
        xaxis_title='company_size',
        boxmode='group'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)

    fig_dict = json.loads(fig_json)
    return fig_dict