# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 16:41:09

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure Date is datetime (should be already, but safe)
    data = data_raw.copy()
    data['Date'] = pd.to_datetime(data['Date'])
    
    # Sort data by Date to ensure lines are plotted in order
    data = data.sort_values(by=['Category', 'Date'])
    
    # Create figure
    fig = go.Figure()
    
    # Get unique categories
    categories = data['Category'].unique()
    
    # Add a line for each category with markers and smooth lines
    for cat in categories:
        df_cat = data[data['Category'] == cat]
        fig.add_trace(go.Scatter(
            x=df_cat['Date'],
            y=df_cat['Cumulative Sales'],
            mode='lines+markers',
            name=cat,
            line_shape='spline'
        ))
    
    # Update layout for title, axis labels, legend
    fig.update_layout(
        title="Cumulative Sales Growth Over Time by Product Category (2025)",
        xaxis_title="Date",
        yaxis_title="Cumulative Sales",
        legend_title="Category",
        xaxis=dict(
            type='date',
            tickformat='%b %d',
            tickangle=45,
            showgrid=True,
            rangeslider_visible=False,
            dtick="M1"
        ),
        yaxis=dict(
            showgrid=True
        ),
        template='plotly_white',
        hovermode='x unified'
    )
    
    # Convert fig to json dict and return
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    
    return fig_dict