# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:10:37

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    fig.add_trace(go.Box(
        x=data_raw["Sub-Category"],
        y=data_raw["Profit"],
        boxpoints='outliers',
        marker=dict(color='royalblue'),
        line=dict(color='royalblue'),
        name="Profit Distribution"
    ))

    fig.update_layout(
        title="Distribution of Profit across Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Profit",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict