# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:55:42

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Calculate the average salary for each experience level
    avg_salary = data_raw.groupby('experience_level', as_index=False)['salary_in_usd'].mean()

    # Create the bar chart with bars colored blue
    fig = go.Figure(data=[
        go.Bar(
            x=avg_salary['experience_level'],
            y=avg_salary['salary_in_usd'],
            marker_color='blue'
        )
    ])

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict