# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:45:44

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import json
    import plotly.io as pio




    # Create a bar chart with average_salary_in_usd on y-axis and job_title on x-axis
    fig = go.Figure(data=[
        go.Bar(
            x=data_raw['job_title'],
            y=data_raw['average_salary_in_usd'],
            marker_color='green'
        )
    ])

    # Return the figure as a dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict