# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 19:31:32

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the bar chart with specified parameters
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['Victim_Age_Group'],
                y=data_raw['Avg_Offender_Age'],
                marker_color='blue'
            )
        ],
        layout=go.Layout(
            xaxis_title='Victim_Age_Group',
            yaxis_title='Avg_Offender_Age'
        )
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict