# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 22:42:57

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Filter out rows with missing 'mean' or 'count' values
    df = data_raw.copy()
    df_clean = df.loc[df['mean'].notna() & df['count'].notna()]

    # Create scatter plot with regression trendline using plotly.express
    fig = px.scatter(
        df_clean,
        x='mean',
        y='count',
        trendline='ols',
        title="Scatter Plot of Average Price vs Purchase Quantity with Best-Fit Line",
        labels={
            'mean': "Average Price (mean)",
            'count': "Purchase Quantity (count)"
        },
        template='simple_white'
    )

    # Adjust layout for clarity
    fig.update_layout(
        title=dict(x=0.5),
        xaxis=dict(showgrid=True, zeroline=False),
        yaxis=dict(showgrid=True, zeroline=False)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict