# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:51:30

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Calculate the average remote_ratio for each job_title
    avg_remote_ratio = data_raw.groupby('job_title')['remote_ratio'].mean().reset_index()

    # Create a bar chart with blue bars
    fig = go.Figure(data=[
        go.Bar(
            x=avg_remote_ratio['job_title'],
            y=avg_remote_ratio['remote_ratio'],
            marker_color='blue'
        )
    ])

    # Update layout for better readability
    fig.update_layout(
        xaxis_title='job_title',
        yaxis_title='Average remote_ratio',
        xaxis_tickangle=-45,
        margin=dict(b=200),
        height=600
    )

    # Convert the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict