# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:52:51

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Calculate the average salary per experience level
    avg_salary = data_raw.groupby('experience_level')['salary_in_usd'].mean().reset_index()

    # Create the bar chart
    fig = go.Figure(data=[
        go.Bar(
            x=avg_salary['experience_level'],
            y=avg_salary['salary_in_usd'],
            marker_color='blue'
        )
    ])

    # Convert the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict