# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:54:59

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Calculate the average salary_in_usd for each employment_type
    df = data_raw
    avg_salary = df.groupby('employment_type')['salary_in_usd'].mean().reset_index()

    # Create a bar chart with employment_type on x-axis and avg salary on y-axis
    fig = go.Figure(data=[
        go.Bar(
            x=avg_salary['employment_type'],
            y=avg_salary['salary_in_usd'],
            marker_color='blue'
        )
    ])

    # Convert figure to JSON-compatible dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict