# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:39:04

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure the review_month column is sorted chronologically
    df = data_raw.copy()
    df['review_month'] = pd.to_datetime(df['review_month'])
    df = df.sort_values('review_month')

    # Create the line chart
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=df['review_month'],
        y=df['avg_rating'],
        mode='lines+markers',
        name='Average Rating'
    ))

    fig.update_layout(
        title='Trend of Average Rating Over Time',
        xaxis_title='Review Month',
        yaxis_title='Average Rating',
        xaxis=dict(
            tickformat='%Y-%m',
            tickangle=45,
            type='date'
        ),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict