# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:09:48

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    sub_categories = data_raw['Sub-Category'].unique()
    for sub_cat in sorted(sub_categories):
        fig.add_trace(go.Box(
            y=data_raw.loc[data_raw['Sub-Category'] == sub_cat, 'Profit'],
            name=sub_cat,
            boxpoints='outliers',
            marker=dict(size=4),
            line=dict(width=1),
            boxmean=True
        ))

    fig.update_layout(
        title="Distribution of Profit across Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Profit",
        xaxis=dict(tickangle=-45),
        template='plotly_white',
        margin=dict(t=60, b=100)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict