# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:10:09

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create boxplot with x as Sub-Category and y as mean
    fig = go.Figure()

    fig.add_trace(go.Box(
        x=data_raw["Sub-Category"],
        y=data_raw["mean"],
        boxpoints='all',  # show all points
        jitter=0.5,
        pointpos=-1.8,
        marker=dict(color='blue'),
        line=dict(color='blue'),
        name="mean"
    ))

    fig.update_layout(
        title="Distribution of mean across Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="mean"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict