# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-27 17:56:54

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is expected to be a DataFrame indexed by Payment Method with columns Cancelled, Completed, Pending
    df = data_raw.copy()
    df.index.name = 'Payment Method'
    df = df.reset_index()

    # Define the order of payment methods and statuses for consistent plotting
    payment_methods = ["Credit Card", "Debit Card", "Gift Card", "PayPal"]
    status_categories = ["Cancelled", "Completed", "Pending"]

    # Ensure the DataFrame is sorted by the payment_methods order
    df['Payment Method'] = pd.Categorical(df['Payment Method'], categories=payment_methods, ordered=True)
    df = df.sort_values('Payment Method')

    # Colors for each status category
    colors = {
        "Cancelled": "#d62728",  # red
        "Completed": "#2ca02c",  # green
        "Pending": "#1f77b4"     # blue
    }

    fig = go.Figure()

    # Add a bar trace for each Status category stacked by Payment Method
    for status in status_categories:
        fig.add_trace(go.Bar(
            x=df['Payment Method'],
            y=df[status],
            name=status,
            marker_color=colors[status]
        ))

    fig.update_layout(
        barmode='stack',
        title="Proportion of Status Categories by Payment Method",
        xaxis_title="Payment Method",
        yaxis_title="Proportion of Status",
        yaxis=dict(range=[0, 1]),
        legend_title="Status",
        template="simple_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict