# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:23:36

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Ensure we have correct column names and types
    df = pd.DataFrame(data_raw)

    # Since the data only has summary statistics (q1, median, q3) per Report Type,
    # we will visualize these as box-like shapes to represent the distribution.

    fig = go.Figure()

    for idx, row in df.iterrows():
        # Create a synthetic boxplot using only q1, median, and q3
        # Plotly's Box trace expects raw data, so we simulate with 3 points
        fig.add_trace(go.Box(
            y=[row['q1'], row['median'], row['q3']],
            x=[row['Report Type']] * 3,
            name=str(row['Report Type']),
            boxpoints=False,
            line=dict(color='blue'),
            marker=dict(color='lightblue'),
            showlegend=False,
            quartilemethod="inclusive"
        ))

        # Overlay median as a scatter for emphasis
        fig.add_trace(go.Scatter(
            x=[row['Report Type']],
            y=[row['median']],
            mode='markers+text',
            marker=dict(color='red', size=10),
            text=[f"{row['median']}"],
            textposition="top center",
            showlegend=False
        ))

    fig.update_layout(
        title="Distribution, Median, and Interquartile Range by Report Type",
        yaxis_title="Value",
        xaxis_title="Report Type",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict