# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:16:48

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create a box plot with salary_in_usd on y-axis and experience_level on x-axis, color blue
    fig = go.Figure()

    # Get unique experience levels to create box traces
    experience_levels = data_raw['experience_level'].dropna().unique()

    for level in experience_levels:
        level_data = data_raw[data_raw['experience_level'] == level]['salary_in_usd']
        fig.add_trace(
            go.Box(
                y=level_data,
                name=level,
                marker_color='blue'
            )
        )

    # Update layout for clarity
    fig.update_layout(
        xaxis_title='experience_level',
        yaxis_title='salary_in_usd',
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict