# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:52:32

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data for stacked bar chart
    races = data_raw['Offender_Race'].unique()
    genders = data_raw['Offender_Gender'].unique()

    # Ensure races and genders order is preserved as in data
    races = list(data_raw['Offender_Race'])
    races = pd.Categorical(data_raw['Offender_Race'], categories=data_raw['Offender_Race'].unique(), ordered=True)
    categories = data_raw['Offender_Race'].unique()

    # Pivot data for stacking
    pivot_df = data_raw.pivot(index='Offender_Race', columns='Offender_Gender', values='offender_count').fillna(0)

    # Create traces for each gender
    traces = []
    for gender in pivot_df.columns:
        traces.append(
            go.Bar(
                x=pivot_df.index,
                y=pivot_df[gender],
                name=gender,
            )
        )

    fig = go.Figure(data=traces)
    fig.update_layout(
        barmode='stack',
        title='Offender Count by Race and Gender',
        xaxis_title='Offender Race',
        yaxis_title='Offender Count'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict