# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 02:51:00

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Sort data by avg_100g_USD descending
    data_sorted = data_raw.sort_values('avg_100g_USD', ascending=False)

    fig = go.Figure(
        data=[
            go.Bar(
                x=data_sorted['loc_country'],
                y=data_sorted['avg_100g_USD'],
                marker_color='teal'
            )
        ]
    )

    fig.update_layout(
        title='Average 100g USD Price by Country',
        xaxis_title='Country',
        yaxis_title='Average Price (USD per 100g)',
        xaxis_tickangle=45,
        template='plotly_white',
        margin=dict(l=60, r=30, t=60, b=120)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict