# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 03:30:08

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data: use only the needed columns and drop any rows with missing values in those columns
    df = data_raw[['100g_USD', 'rating']].dropna()

    # Create scatter plot
    fig = go.Figure(data=go.Scatter(
        x=df['100g_USD'],
        y=df['rating'],
        mode='markers',
        marker=dict(
            color='blue',
            size=6,
            opacity=0.7
        )
    ))

    # Update layout with title and axis labels
    fig.update_layout(
        title="Scatter Plot of 100g_USD vs Rating",
        xaxis_title="Price per 100g (USD)",
        yaxis_title="Rating"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict