# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:45:57

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Calculate average Budget by Country and Environmental Impact
    avg_budget = data_raw.groupby(['Country', 'Environmental Impact'], as_index=False)['Budget (in Billion $)'].mean()

    countries = avg_budget['Country'].unique()
    env_impacts = avg_budget['Environmental Impact'].unique()

    # Prepare traces for each Environmental Impact category
    traces = []
    for impact in env_impacts:
        impact_data = avg_budget[avg_budget['Environmental Impact'] == impact]
        # Make sure ordering corresponds to countries order
        budget_vals = [impact_data[impact_data['Country'] == c]['Budget (in Billion $)'].values[0] if c in impact_data['Country'].values else None for c in countries]
        traces.append(go.Bar(
            name=impact,
            x=countries,
            y=budget_vals
        ))

    # Create grouped bar chart
    fig = go.Figure(data=traces)
    fig.update_layout(
        barmode='group',
        xaxis_title='Country',
        yaxis_title='Average Budget (in Billion $)',
        title='Average Budget by Country grouped by Environmental Impact'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict