# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:36:10

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure correct order of Offender_Race for reproducibility
    x = data_raw["Offender_Race"].tolist()
    y_female = data_raw["FEMALE"].tolist()
    y_male = data_raw["MALE"].tolist()

    fig = go.Figure(data=[
        go.Bar(
            name='FEMALE',
            x=x,
            y=y_female,
            marker_color='rgb(222, 45, 38, 0.8)'
        ),
        go.Bar(
            name='MALE',
            x=x,
            y=y_male,
            marker_color='rgb(49,130,189, 0.8)'
        )
    ])

    fig.update_layout(
        barmode='group',
        title='Counts of Offender_Race by Gender (FEMALE vs MALE)',
        xaxis_title='Offender_Race',
        yaxis_title='Count',
        legend_title='Gender'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict