# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:13:01

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    # Create violin plot grouped by Sub-Category
    for sub_cat in data_raw['Sub-Category'].unique():
        fig.add_trace(go.Violin(
            y=data_raw.loc[data_raw['Sub-Category'] == sub_cat, 'Profit'],
            x=np.repeat(sub_cat, data_raw.loc[data_raw['Sub-Category'] == sub_cat].shape[0]),
            name=sub_cat,
            box_visible=True,
            meanline_visible=True,
            spanmode='hard',
            line_color='black'
        ))

    fig.update_layout(
        title="Distribution of Profit across Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Profit",
        violingap=0,
        violingroupgap=0,
        violinmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict