# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 16:05:49

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure data_raw is a DataFrame
    df = pd.DataFrame(data_raw)
    
    # Sort data by Status to keep consistent order if needed
    status_order = ['Completed', 'Pending', 'Cancelled']
    df['Status'] = pd.Categorical(df['Status'], categories=status_order, ordered=True)
    df = df.sort_values('Status')
    
    # Define distinct colors for each status
    colors = {
        'Completed': 'green',
        'Pending': 'orange',
        'Cancelled': 'red'
    }
    bar_colors = [colors[status] for status in df['Status']]
    
    # Create bar chart
    fig = go.Figure(data=go.Bar(
        x=df['Status'],
        y=df['Order Count'],
        marker_color=bar_colors
    ))
    
    # Update layout with title and axis labels
    fig.update_layout(
        title="Count of Orders by Status Category",
        xaxis_title="Order Status",
        yaxis_title="Number of Orders",
        yaxis=dict(range=[0, max(df['Order Count'].max() * 1.1, 10)])  # start y-axis at 0
    )
    
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    
    return fig_dict