# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-28 12:23:51

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Pivot the data to create a matrix with Month on y-axis and Day of Week on x-axis
    pivot_table = data_raw.pivot(index='Month', columns='Day of Week', values='Average Total Sales')

    # Sort indices to ensure correct order
    pivot_table = pivot_table.sort_index()
    pivot_table = pivot_table.reindex(columns=sorted(pivot_table.columns))

    # Convert the indices and columns to strings for categorical axis labels
    y_labels = pivot_table.index.astype(str)
    x_labels = pivot_table.columns.astype(str)

    # Create heatmap
    fig = go.Figure(data=go.Heatmap(
        z=pivot_table.values,
        x=x_labels,
        y=y_labels,
        colorscale='Viridis',
        colorbar=dict(title="Average Total Sales"),
        hovertemplate='Month: %{y}<br>Day of Week: %{x}<br>Avg Sales: %{z}<extra></extra>'
    ))

    fig.update_layout(
        title="Heatmap of Average Total Sales by Month and Day of Week",
        xaxis_title="Day of Week (0=Sunday to 6=Saturday)",
        yaxis_title="Month",
        xaxis=dict(tickmode='array', tickvals=x_labels, ticktext=x_labels),
        yaxis=dict(tickmode='array', tickvals=y_labels, ticktext=y_labels),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict