# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 19:56:26

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data
    df = data_raw.copy()

    fig = go.Figure(
        go.Bar(
            x=df["Sub-Category"],
            y=df["Total Quantity"],
            marker_color='indianred'
        )
    )

    fig.update_layout(
        title="Total Quantity Sold for Each Sub-Category",
        xaxis_title="Sub-Category",
        yaxis_title="Total Quantity",
        xaxis_tickangle=-45,
        template="plotly_white",
        margin=dict(t=60, b=120)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict