# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:15:10

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create a bar chart of average_salary_in_usd grouped by job_title
    fig = go.Figure()

    # Add bars: each job_title with corresponding average_salary_in_usd
    fig.add_trace(
        go.Bar(
            x=data_raw['job_title'],
            y=data_raw['average_salary_in_usd'],
            name='Average Salary',
        )
    )

    # Update layout for better readability
    fig.update_layout(
        title='Average Salary by Job Title',
        xaxis_title='Job Title',
        yaxis_title='Average Salary in USD',
        xaxis_tickangle=-45,
        margin=dict(b=150),
        height=600
    )

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict