# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-18 17:15:56

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure 'year_month' is sorted in time order for the x-axis
    # Convert year_month to datetime for sorting and back to string for display
    data = data_raw.copy()
    data['year_month_dt'] = pd.to_datetime(data['year_month'], format='%Y-%m')
    data = data.sort_values('year_month_dt')

    # Define the roast categories to plot
    roast_categories = ["Dark", "Light", "Medium", "Medium-Dark", "Medium-Light"]

    fig = go.Figure()

    # Add a line for each roast category
    for roast in roast_categories:
        fig.add_trace(
            go.Scatter(
                x=data['year_month'],
                y=data[roast],
                mode='lines+markers',
                name=roast,
                connectgaps=True  # Connect points even if NaNs in-between
            )
        )

    fig.update_layout(
        title="Trend of Average Price over Year-Month by Roast Category",
        xaxis_title="Year-Month",
        yaxis_title="Average Price (100g_USD)",
        legend_title="Roast Category",
        xaxis=dict(tickangle=45),
        template="plotly_white",
        hovermode="x unified"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict