# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:28:32

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Assuming data_raw is a pandas DataFrame with the column 'ARRESTED'
    # Create a count of each ARRESTED category
    arrest_counts = data_raw['ARRESTED'].value_counts().reset_index()
    arrest_counts.columns = ['ARRESTED', 'Count']

    # Generate a grouped bar chart
    fig = go.Figure(data=[
        go.Bar(
            x=arrest_counts['ARRESTED'].astype(str),
            y=arrest_counts['Count'],
            marker_color='green'
        )
    ])

    # Update layout for clarity
    fig.update_layout(
        xaxis_title='ARRESTED',
        yaxis_title='Count',
        title='Count of ARRESTED categories'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict