# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:55:06

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure Offender_Race is string (for categorical x-axis)
    data_raw['Offender_Race'] = data_raw['Offender_Race'].astype(str)

    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['Offender_Race'],
                y=data_raw['Count'],
                marker_color='royalblue'
            )
        ]
    )

    fig.update_layout(
        title="Frequency of Offender_Race",
        xaxis_title="Offender_Race",
        yaxis_title="Count",
        bargap=0.2,
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict