# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 23:19:44

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Convert input to DataFrame if not already
    df = pd.DataFrame(data_raw)

    # Check if there are at least two columns
    if df.shape[1] < 2:
        raise ValueError("Input data must have at least two columns for x and y axes.")

    # Use column names if available, otherwise use positional indexing
    x_col = df.columns[1]
    y_col = df.columns[0]

    fig = go.Figure()
    fig.add_trace(go.Box(
        y=df[y_col],
        x=df[x_col],
        boxpoints='all',  # show all points
        jitter=0.5,
        pointpos=-1.8
    ))

    fig.update_layout(
        xaxis_title=str(x_col),
        yaxis_title=str(y_col),
        title=f"Box Plot of Column '{y_col}' by Column '{x_col}'"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict