# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 19:26:53

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the scatter plot with Victim_Age on y-axis, Offender_Age on x-axis, points colored blue
    fig = go.Figure(data=go.Scatter(
        x=data_raw['Offender_Age'],
        y=data_raw['Victim_Age'],
        mode='markers',
        marker=dict(color='blue')
    ))

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict