# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 18:52:25

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is expected to be a DataFrame with index as categories and columns as price ranges

    # Define the price ranges in the required order
    price_ranges = ['0-50', '51-100', '101-200', '201-500', '501-1000', '1001+']
    categories = data_raw.index.tolist()

    # Create a grouped bar chart
    fig = go.Figure()

    # Assign distinct colors for each category
    colors = {
        'Category_Clothing': '#1f77b4',       # blue
        'Category_Electronics': '#ff7f0e',    # orange
        'Category_Footwear': '#2ca02c',       # green
        'Category_Home Appliances': '#d62728' # red
    }

    for category in categories:
        fig.add_trace(
            go.Bar(
                name=category,
                x=price_ranges,
                y=data_raw.loc[category, price_ranges].values,
                marker_color=colors.get(category, None)
            )
        )

    # Update layout for grouped bar chart and titles
    fig.update_layout(
        barmode='group',
        title="Distribution of Price Ranges by Product Category",
        xaxis_title="Price Range (in currency units)",
        yaxis_title="Percentage Distribution (%)",
        legend_title="Product Category"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict