# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 11:49:56

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data: use columns "roast" and "100g_USD"
    df = data_raw.copy()

    # Create boxplot figure
    fig = go.Figure()

    # Get unique roast categories in order of appearance
    roast_categories = df['roast'].unique()

    for roast_cat in roast_categories:
        fig.add_trace(
            go.Box(
                y=df.loc[df['roast'] == roast_cat, '100g_USD'],
                name=roast_cat,
                boxpoints='outliers',
                marker=dict(size=4),
                line=dict(width=1),
                boxmean=False
            )
        )

    fig.update_layout(
        title="Distribution of 100g_USD by Roast",
        xaxis_title="Roast",
        yaxis_title="Price per 100g (USD)",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict