# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:53:43

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create a boxplot of salary_in_usd by company_size, with blue fill color
    fig = go.Figure()

    fig.add_trace(
        go.Box(
            y=data_raw['salary_in_usd'],
            x=data_raw['company_size'],
            fillcolor='blue',
            line=dict(color='blue'),
            marker=dict(color='blue'),
            name='Salary Distribution'
        )
    )

    # Update layout for better visualization
    fig.update_layout(
        xaxis_title='Company Size',
        yaxis_title='Salary in USD',
        boxmode='group',
        title='Salary Distribution by Company Size'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict