# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:18:35

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Aggregate data: mean vote_average grouped by genres and country
    agg_df = data_raw.groupby(['genres', 'country'], as_index=False)['vote_average'].mean()

    # To create a grouped bar chart with many countries, we must consider the number of countries.
    # Since there are 134 unique countries, plotting all will be cluttered.
    # To keep the chart readable, let's select top 5 countries by number of entries in data_raw.
    top_countries = data_raw['country'].value_counts().nlargest(5).index.tolist()
    filtered_df = agg_df[agg_df['country'].isin(top_countries)]

    # Pivot data to have genres as x-axis and countries as groups (each country is a separate trace)
    pivot_df = filtered_df.pivot(index='genres', columns='country', values='vote_average').fillna(0)

    genres = pivot_df.index.tolist()
    countries = pivot_df.columns.tolist()

    fig = go.Figure()
    for country in countries:
        fig.add_trace(go.Bar(
            x=genres,
            y=pivot_df[country],
            name=country
        ))

    fig.update_layout(
        barmode='group',
        title="Average vote_average across genres grouped by country",
        xaxis_title="Genres",
        yaxis_title="Average vote_average",
        xaxis={'categoryorder':'category ascending'},
        legend_title_text='Country',
        template='plotly_white',
        height=600,
        width=900
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict