# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 18:29:07

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Data cleaning: ensure Month is treated as categorical with specified order
    data = data_raw.copy()
    data['Month'] = data['Month'].astype(str)
    month_order = ['2', '3', '4']
    data = data.set_index('Month').reindex(month_order).reset_index()

    # Prepare product categories and colors
    categories = ['Clothing', 'Electronics', 'Footwear', 'Home Appliances']
    colors = ['#636EFA', '#EF553B', '#00CC96', '#AB63FA']

    # Create grouped bar chart
    fig = go.Figure()

    for cat, color in zip(categories, colors):
        fig.add_trace(go.Bar(
            x=data['Month'],
            y=data[cat],
            name=cat,
            marker_color=color
        ))

    # Update layout for grouped bars and labels
    fig.update_layout(
        barmode='group',
        title="Total Sales Amounts by Product Category and Month (2025) to Identify Seasonal Trends",
        xaxis_title="Month",
        yaxis_title="Total Sales Amount",
        legend_title="Product Category"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict