# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:05:46

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create a boxplot of salary_in_usd grouped by experience_level with blue color
    fig = go.Figure()

    fig.add_trace(go.Box(
        y=data_raw['salary_in_usd'],
        x=data_raw['experience_level'],
        boxpoints='outliers',
        marker_color='blue',
        line_color='blue',
        boxmean='sd'
    ))

    # Update layout to set title and axis labels
    fig.update_layout(
        title='Salary Distribution by Experience Level',
        xaxis_title='Experience Level',
        yaxis_title='Salary in USD',
        boxmode='group'
    )

    # Return the figure as a JSON-compatible dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict