# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:17:41

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Count the occurrences of each unique value in the ARRESTED column
    counts = data_raw['ARRESTED'].value_counts().reset_index()
    counts.columns = ['Disposition', 'Count']

    # Create a bar chart with specified parameters
    fig = go.Figure(data=[
        go.Bar(
            x=counts['Disposition'],
            y=counts['Count'],
            marker_color='blue'
        )
    ])

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict