# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 20:18:49

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create box plot of salary_in_usd vs experience_level with blue color
    fig = go.Figure()
    fig.add_trace(
        go.Box(
            y=data_raw['salary_in_usd'],
            x=data_raw['experience_level'],
            boxpoints='outliers',
            marker=dict(color='blue'),
            line=dict(color='blue'),
            name='Salary by Experience Level'
        )
    )

    # Update layout for better visualization
    fig.update_layout(
        yaxis_title='salary_in_usd',
        xaxis_title='experience_level',
        boxmode='group'
    )

    # Convert figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict