# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 00:03:52

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Convert Year-Month to datetime for proper sorting and plotting
    data = data_raw.copy()
    data['Year-Month'] = pd.to_datetime(data['Year-Month'], format='%Y-%m')

    # Aggregate Amount by Year-Month by sum (though data is unique per month here)
    agg_data = data.groupby('Year-Month', as_index=False)['Amount'].sum()

    # Sort by Year-Month ascending
    agg_data = agg_data.sort_values('Year-Month', ascending=True)

    # Create line chart
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=agg_data['Year-Month'],
        y=agg_data['Amount'],
        mode='lines+markers',
        line=dict(color='blue'),
        marker=dict(size=6),
        name='Total Amount'
    ))

    fig.update_layout(
        title='Trend of Total Amount Over Year-Month',
        xaxis_title='Year-Month',
        yaxis_title='Amount',
        xaxis=dict(
            tickformat='%Y-%m',
            tickangle=45,
            dtick="M1",
            showgrid=True
        ),
        yaxis=dict(showgrid=True),
        template='plotly_white',
        margin=dict(l=60, r=40, t=80, b=100)
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict