# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 03:28:53

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure(
        data=go.Scatter(
            x=data_raw["100g_USD"],
            y=data_raw["rating"],
            mode='markers',
            marker=dict(color='blue', opacity=0.7)
        )
    )

    fig.update_layout(
        title="Scatter plot of rating vs 100g_USD",
        xaxis_title="100g_USD",
        yaxis_title="rating",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict