# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:30:23

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Group data by Offender_Gender and sum ARRESTED counts
    grouped_data = data_raw.groupby('Offender_Gender', as_index=False)['ARRESTED'].sum()

    # Create a grouped bar chart with Offender_Gender on x-axis and ARRESTED count on y-axis
    fig = go.Figure(
        data=[
            go.Bar(
                x=grouped_data['Offender_Gender'],
                y=grouped_data['ARRESTED'],
                marker_color='green'
            )
        ],
        layout=go.Layout(
            xaxis_title='Offender_Gender',
            yaxis_title='Count of ARRESTED',
            title='Arrested Counts by Offender Gender'
        )
    )

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict