# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-26 16:27:58

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Extract the orbital periods from the dataframe
    orbital_periods = data_raw["Orbital Period Days"]

    # Define number of bins for histogram
    # Considering the range is approx 0.09 to 139 days, 
    # using 40 bins will give a clear distribution visualization
    nbins = 40

    # Create the histogram figure
    fig = go.Figure(
        data=[
            go.Histogram(
                x=orbital_periods,
                nbinsx=nbins,
                marker=dict(color='blue'),
                opacity=0.75
            )
        ]
    )

    # Set the layout titles and axis labels
    fig.update_layout(
        title="Distribution of Orbital Periods of Planets (in Days)",
        xaxis_title="Orbital Period (Days)",
        yaxis_title="Number of Planets",
        xaxis=dict(type='linear'),
        yaxis=dict(type='linear'),
        bargap=0.1
    )

    # Convert figure to JSON string and then to dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict