# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:23:53

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Calculate the average salary for each job_title
    avg_salary = data_raw.groupby('job_title')['salary_in_usd'].mean().reset_index()

    # Create the bar chart with Plotly Graph Objects
    fig = go.Figure(
        data=[
            go.Bar(
                x=avg_salary['job_title'],
                y=avg_salary['salary_in_usd'],
                marker_color='blue'
            )
        ],
        layout=go.Layout(
            xaxis_title='job_title',
            yaxis_title='Average salary_in_usd',
            title='Average Salary by Job Title'
        )
    )

    # Convert the figure to JSON and then to a dictionary
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict