# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:29:20

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is expected to be a DataFrame with index as Country and columns "Manned" and "Unmanned"
    df = data_raw.copy()
    countries = df.index.tolist()

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=countries,
        y=df["Manned"],
        name="Manned",
        marker_color='indianred'
    ))

    fig.add_trace(go.Bar(
        x=countries,
        y=df["Unmanned"],
        name="Unmanned",
        marker_color='lightsalmon'
    ))

    fig.update_layout(
        barmode='group',
        xaxis_title="Country",
        yaxis_title="Success Rate (%)",
        title="Success Rate Comparison of Manned vs Unmanned Missions by Country",
        xaxis_tickangle=-45
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict