# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:43:26

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=data_raw["Year"],
        y=data_raw["Success Rate (%)"],
        mode='lines+markers',
        name='Success Rate (%)'
    ))

    fig.update_layout(
        title="Trend of Success Rate (%) Over Year",
        xaxis_title="Year",
        yaxis_title="Success Rate (%)",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict