# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 19:58:34

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Create box plot using plotly.express
    fig = px.box(
        data_raw,
        x="Category",
        y="Quantity",
        title="Distribution of Quantity Sold by Category",
        labels={"Category": "Category", "Quantity": "Quantity"}
    )

    fig.update_layout(
        xaxis_title="Category",
        yaxis_title="Quantity"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict