# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:35:15

def data_visualization(data_raw):
    import pandas as pd
    import json
    import plotly.graph_objects as go
    import plotly.io as pio




    # Create the boxplot with specified parameters
    fig = go.Figure()
    fig.add_trace(go.Box(
        y=data_raw['salary_in_usd'],
        x=data_raw['experience_level'],
        boxmean='sd',  # Optional: display mean and std if desired
        marker_color='blue'
    ))

    # Update layout for better aesthetics and labels
    fig.update_layout(
        xaxis_title='experience_level',
        yaxis_title='salary_in_usd',
        boxmode='group',
        title='Salary Distribution by Experience Level'
    )

    # Convert the figure to JSON
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict