# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-19 18:25:04

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Copy data to avoid modifying original
    df = data_raw.copy()

    # Identify top 3 most frequent roasters by count of appearances in dataset
    top_roasters = df['roaster'].value_counts().nlargest(3).index.tolist()

    # Filter dataframe to only include top 3 roasters
    df_top = df[df['roaster'].isin(top_roasters)]

    # Create boxplot figure
    fig = go.Figure()

    for roaster in top_roasters:
        roaster_data = df_top[df_top['roaster'] == roaster]['rating']
        fig.add_trace(go.Box(
            y=roaster_data,
            name=roaster,
            boxpoints='outliers',
            marker=dict(size=4),
            line=dict(width=1)
        ))

    fig.update_layout(
        title="Distribution of Ratings for Top 3 Most Frequent Roaster Categories",
        xaxis_title="Roaster",
        yaxis_title="Rating",
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict