# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:14:59

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Create bar chart with error bars (IQR)
    fig = go.Figure()
    fig.add_trace(
        go.Bar(
            x=data_raw['Report Type'],
            y=data_raw['median'],
            error_y=dict(
                type='data',
                array=data_raw['IQR'],
                visible=True
            ),
            marker_color='steelblue'
        )
    )

    fig.update_layout(
        title='Median and IQR by Report Type',
        xaxis_title='Report Type',
        yaxis_title='median',
        bargap=0.4
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict