# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:40:47

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data
    df = data_raw.copy()

    # Create line chart
    fig = go.Figure()

    fig.add_trace(go.Scatter(
        x=df['Year'],
        y=df['Success Rate (%)'],
        mode='lines+markers',
        line=dict(color='blue'),
        marker=dict(size=6),
        name='Success Rate (%)'
    ))

    # Update layout with titles
    fig.update_layout(
        title="Trend of Success Rate (%) Over Year",
        xaxis_title="Year",
        yaxis_title="Success Rate (%)",
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict