# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:38:48

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure data is in DataFrame format
    df = pd.DataFrame(data_raw)

    # Create bar chart
    fig = go.Figure(
        data=[
            go.Bar(
                x=df["Offender_Gender"],
                y=df["mean"],
                marker_color=['#636EFA', '#EF553B']
            )
        ]
    )

    # Update layout with titles and axis labels
    fig.update_layout(
        title="Mean Age of Offenders by Gender",
        xaxis_title="Offender Gender",
        yaxis_title="Mean Age",
        xaxis=dict(type='category'),
        template="plotly_white"
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict