# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:52:03

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.express as px
    import plotly.io as pio





    # Step 1: Apply filters
    df = data_raw.copy()
    df = df[
        (df['Age_Type'] == 'Offender') &
        (df['Group_By'] == 'Offender_Race')
    ]

    # Step 2: Select needed columns and drop missing values
    # We need 'Offender_Race' and 'mean'
    df_box = df[['Offender_Race', 'mean']].dropna(subset=['Offender_Race', 'mean'])

    # Step 3: Create box plot
    fig = px.box(
        df_box,
        x='Offender_Race',
        y='mean',
        points='outliers',
        title='Distribution of Offender Mean Age by Offender Race',
        labels={'mean': 'Mean Age', 'Offender_Race': 'Offender Race'}
    )

    fig.update_layout(
        xaxis_title='Offender Race',
        yaxis_title='Mean Age',
        boxmode='group'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict