# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 03:11:20

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure review_date is datetime (precaution)
    if not np.issubdtype(data_raw['review_date'].dtype, np.datetime64):
        data_raw['review_date'] = pd.to_datetime(data_raw['review_date'])

    # Create line chart
    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=data_raw['review_date'],
            y=data_raw['average_100g_USD'],
            mode='lines+markers',
            name='average_100g_USD'
        )
    )

    fig.update_layout(
        title='Trend of average_100g_USD Over review_date',
        xaxis_title='review_date',
        yaxis_title='average_100g_USD',
        xaxis=dict(
            tickformat='%Y-%m',
            tickmode='auto'
        ),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict