# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:47:17

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio
    from plotly.colors import qualitative, sequential





    # Since only one OffenderStatus exists, stacking is trivial but we implement as requested
    # Prepare data for bar plot
    x_vals = data_raw['OffenderGender']
    y_vals = data_raw['count']
    offender_status = data_raw['OffenderStatus'].unique()[0]

    # Get color from the Greens palette

    # Use a mid-tone green
    color = sequential.Greens[4] if len(sequential.Greens) > 4 else "#2ca02c"

    fig = go.Figure()

    fig.add_trace(
        go.Bar(
            x=x_vals,
            y=y_vals,
            name=offender_status,
            marker_color=color,
            orientation='v'
        )
    )

    fig.update_layout(
        barmode='stack',
        title='Distribution of Offender Status by Gender',
        xaxis_title='Gender',
        yaxis_title='Count of Offender Status',
        legend_title='Offender Status',
        legend=dict(
            title='Offender Status'
        ),
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict