# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 19:49:12

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create a box plot of salary_in_usd by experience_level, colored blue
    fig = go.Figure()

    # Add box plot trace
    fig.add_trace(
        go.Box(
            x=data_raw['experience_level'],
            y=data_raw['salary_in_usd'],
            marker_color='blue',
            boxmean='sd'
        )
    )

    # Update layout for clarity
    fig.update_layout(
        xaxis_title='experience_level',
        yaxis_title='salary_in_usd',
        boxmode='group'
    )

    # Convert figure to JSON and back to dict
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict