# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-15 21:38:18

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the bar chart with specified parameters
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['employment_type'],
                y=data_raw['salary_in_usd'],
                marker_color='blue'
            )
        ]
    )

    # Convert the figure to JSON format
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict