# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 22:31:51

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # data_raw is assumed to be a DataFrame with index as Mission Types and columns Manned, Unmanned
    df = data_raw.copy()
    df.reset_index(inplace=True)
    df.rename(columns={'index': 'Mission Type'}, inplace=True)
    if 'index' in df.columns:
        df.rename(columns={'index': 'Mission Type'}, inplace=True)
    # If the index name is not set, use index name from df.index.name or set explicitly:
    if df.columns[0] != 'Mission Type':
        df.rename(columns={df.columns[0]: 'Mission Type'}, inplace=True)

    mission_types = df['Mission Type'].tolist()

    fig = go.Figure()

    fig.add_trace(go.Bar(
        x=mission_types,
        y=df['Manned'],
        name='Manned'
    ))

    fig.add_trace(go.Bar(
        x=mission_types,
        y=df['Unmanned'],
        name='Unmanned'
    ))

    fig.update_layout(
        barmode='group',
        xaxis_title='Mission Types',
        yaxis_title='Duration in Days',
        title='Duration Comparison by Satellite Type and Mission Type'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict