# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-17 19:45:59

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Prepare data: use the columns indicated, no filtering needed as no missing values in these columns
    x = data_raw["100g_USD"]
    y = data_raw["rating"]

    # Create scatter plot with blue circle markers
    fig = go.Figure(
        data=go.Scatter(
            x=x,
            y=y,
            mode='markers',
            marker=dict(
                color='blue',
                symbol='circle',
                size=8,
                line=dict(width=0)
            )
        )
    )

    # Update layout with title and axis labels
    fig.update_layout(
        title="Scatter Plot of Price per 100g (USD) vs. Rating",
        xaxis_title="100g_USD (Price per 100g in USD)",
        yaxis_title="rating (Coffee Rating)",
        template="simple_white"
    )

    # Convert figure to JSON dict for return
    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict