# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 20:24:13

def data_visualization(data_raw):
    import pandas as pd
    import plotly.graph_objects as go
    import plotly.io as pio
    import json




    # Create the bar chart with Offender_Gender on x-axis, OffenderStatus on y-axis, and color set to blue
    fig = go.Figure(
        data=[
            go.Bar(
                x=data_raw['Offender_Gender'],
                y=data_raw['count'],
                marker=dict(color='blue')
            )
        ],
        layout=go.Layout(
            xaxis_title='Offender_Gender',
            yaxis_title='OffenderStatus'
        )
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)
    return fig_dict