# Disclaimer: This function was generated by AI. Please review before using.
# Agent Name: data_visualization_agent
# Time Created: 2025-04-16 21:43:38

def data_visualization(data_raw):
    import pandas as pd
    import numpy as np
    import json
    import plotly.graph_objects as go
    import plotly.io as pio





    # Ensure Victim_Age is numeric and drop missing values (though dataset has 0% missing)
    data = data_raw.copy()
    data = data[pd.notnull(data['Victim_Age'])]
    x = data['Victim_Age']

    # Create histogram
    fig = go.Figure(
        data=[go.Histogram(
            x=x,
            nbinsx=30,
            marker_color='steelblue'
        )]
    )

    # Update layout
    fig.update_layout(
        title='Distribution of Victim_Age',
        xaxis_title='Victim_Age',
        yaxis_title='Count',
        bargap=0.05,
        template='plotly_white'
    )

    fig_json = pio.to_json(fig)
    fig_dict = json.loads(fig_json)

    return fig_dict